import { AcEntity } from '../../angular-cesium/models/ac-entity';
import { EditPoint } from './edit-point';
import { AcLayerComponent } from '../../angular-cesium/components/ac-layer/ac-layer.component';
import { Cartesian3 } from '../../angular-cesium/models/cartesian3';
import { CircleEditOptions, CircleProps } from './circle-edit-options';
import { PointProps, PolylineProps } from './polyline-edit-options';
import { LabelProps } from './label-props';
export declare class EditableCircle extends AcEntity {
    private id;
    private circlesLayer;
    private pointsLayer;
    private arcsLayer;
    private options;
    private _center;
    private _radiusPoint;
    private _outlineArc;
    private doneCreation;
    private _enableEdit;
    private lastDraggedToPosition;
    private _circleProps;
    private _pointProps;
    private _polylineProps;
    private _labels;
    constructor(id: string, circlesLayer: AcLayerComponent, pointsLayer: AcLayerComponent, arcsLayer: AcLayerComponent, options: CircleEditOptions);
    labels: LabelProps[];
    polylineProps: PolylineProps;
    pointProps: PointProps;
    circleProps: CircleProps;
    readonly center: EditPoint;
    readonly radiusPoint: EditPoint;
    enableEdit: boolean;
    setManually(center: Cartesian3, radiusPoint: Cartesian3, centerPointProp?: PointProps, radiusPointProp?: PointProps, circleProp?: CircleProps): void;
    addPoint(position: Cartesian3): void;
    addLastPoint(position: Cartesian3): void;
    movePoint(toPosition: Cartesian3): void;
    moveCircle(dragStartPosition: Cartesian3, dragEndPosition: Cartesian3): void;
    endMovePolygon(): void;
    getRadius(): number;
    getCenter(): Cartesian3;
    getRadiusPoint(): Cartesian3;
    dispose(): void;
    getId(): string;
    private updateCirclesLayer();
    private updatePointsLayer();
    private updateArcsLayer();
    private createOutlineArc();
}
